services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app:cached
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - api-erp
    networks:
      - princesa

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./api:/app:cached
    networks:
      - princesa

  api-erp:
    build:
      context: ./api-erp
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    volumes:
      - ./api-erp:/app:cached
    networks:
      - princesa

networks:
  princesa:
