version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - supervarejo-net

  # Ajustado o alinhamento do db
  db:
    image: postgres:15-alpine
    container_name: supervarejo-db
    restart: always
    environment:
      POSTGRES_USER: diego_user
      POSTGRES_PASSWORD: diego_password
      POSTGRES_DB: supervarejo_prod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - supervarejo-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    shm_size: '1gb'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      # Injetando as variáveis que o seu knexfile.js pede:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=diego_user
      - DB_PASSWORD=diego_password
      - DB_DATABASE_PROD=supervarejo_prod
    ports:
      - "3333:3333"
    volumes:
      - posters_data:/app/src/database
      - uploads:/app/src/tmp/uploads
    restart: always
    networks:
      - supervarejo-net

  api-erp:
    build:
      context: ./api-erp
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_PROD=${DB_DATABASE_PROD}
    ports:
      - "3334:3334"
    restart: always
    networks:
      - supervarejo-net

volumes:
  posters_data:
  uploads:
  pgdata: # IMPORTANTE: Adicionado para não perder os dados do banco

networks:
  supervarejo-net:
    driver: bridge