version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5173:5173"
    restart: always
    networks:
      - supervarejo-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # --- AJUSTES PARA O PUPPETEER ---
    shm_size: '1gb' # Evita o crash do Chromium em cartazes pesados
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - NODE_ENV=production
    # --------------------------------
    ports:
      - "3333:3333"
    volumes:
      - posters_data:/app/src/database
      - uploads:/app/src/tmp/uploads
    restart: always
    networks:
      - supervarejo-net

  api-erp:
    build:
      context: ./api-erp
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    restart: always
    networks:
      - supervarejo-net

volumes:
  posters_data:
  uploads:

networks:
  supervarejo-net:
    driver: bridge