version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - supervarejo-net

  db:
    image: postgres:15-alpine
    container_name: supervarejo-db
    restart: always
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: princesa@33
      POSTGRES_DB: princesa
    # Removi o ports "5432:5432" por segurança. 
    # A API ainda consegue conectar porque estão na mesma rede.
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - supervarejo-net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    shm_size: '1gb'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - DB_HOST=${DB_HOST}  # <--- FIXO COMO DB (Nome do serviço acima)
      - DB_PORT=6432
      - DB_USER=diego
      - DB_PASSWORD=princesa@33
      - DB_DATABASE_PROD=princesa
    ports:
      - "3333:3333"
    volumes:
      - posters_data:/app/src/database
      - uploads:/app/src/tmp/uploads
    restart: always
    networks:
      - supervarejo-net

  api-erp:
    build:
      context: ./api-erp
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST='192.168.0.198'  # <--- FIXO COMO DB (Nome do serviço acima)
      - DB_PORT=5432
      - DB_USER=diegoscavone
      - DB_PASSWORD=princesa@33
      - DB_DATABASE_PROD=erp
    ports:
      - "3334:3334"
    restart: always
    networks:
      - supervarejo-net

volumes:
  posters_data:
  uploads:
  pgdata:

networks:
  supervarejo-net:
    driver: bridge